// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BbNuHj7LNJj5fonRp-U-PTw5TXpssB4',
    appId: '1:942591259454:web:ca2476c8052f73cfe9326f',
    messagingSenderId: '942591259454',
    projectId: 'nodo-b1ff4',
    authDomain: 'nodo-b1ff4.firebaseapp.com',
    storageBucket: 'nodo-b1ff4.firebasestorage.app',
    measurementId: 'G-DTRMXS2VGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GJxqO1XKc6jbBqxKpz7KI5QqPEd5TxA',
    appId: '1:942591259454:android:557ad5a917863c6de9326f',
    messagingSenderId: '942591259454',
    projectId: 'nodo-b1ff4',
    storageBucket: 'nodo-b1ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfU_EYLaW2P4Er9rU5VVt-hzAqp8zxNzw',
    appId: '1:942591259454:ios:fdcfe6b82a928514e9326f',
    messagingSenderId: '942591259454',
    projectId: 'nodo-b1ff4',
    storageBucket: 'nodo-b1ff4.firebasestorage.app',
    iosBundleId: 'com.example.nodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfU_EYLaW2P4Er9rU5VVt-hzAqp8zxNzw',
    appId: '1:942591259454:ios:fdcfe6b82a928514e9326f',
    messagingSenderId: '942591259454',
    projectId: 'nodo-b1ff4',
    storageBucket: 'nodo-b1ff4.firebasestorage.app',
    iosBundleId: 'com.example.nodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0BbNuHj7LNJj5fonRp-U-PTw5TXpssB4',
    appId: '1:942591259454:web:29d6f417dfccf7fae9326f',
    messagingSenderId: '942591259454',
    projectId: 'nodo-b1ff4',
    authDomain: 'nodo-b1ff4.firebaseapp.com',
    storageBucket: 'nodo-b1ff4.firebasestorage.app',
    measurementId: 'G-6P8GXBK09D',
  );
}
